### ISSUE TITLE
Deleting a file from a container

### ISSUE THREAD

**Issue by TonyBogdanov** [ashleyhood/php-lxd#18]
Looks like deleting a file inside a container is not yet implemented, although supported according to the docs: https://github.com/lxc/lxd/blob/master/doc/rest-api.md#delete-pathpathinsidethecontainer

**Comment by ashleyhood** [comment]
@TonyBogdanov would you be willing to submit a PR for this?

**Comment by ashleyhood** [comment]
@TonyBogdanov thanks for the PR
