### ISSUE TITLE
Guzzle adapter dependency

### ISSUE THREAD

**Issue by lcherone** [ashleyhood/php-lxd#2]
Get this error when installing. 

```
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for opensaucesystems/lxd ^0.2.0 -> satisfiable by opensaucesystems/lxd[v0.2.0].
    - opensaucesystems/lxd v0.2.0 requires php-http/client-implementation ^1.0 -> no matching package found.
```

Move the require-dev dependency `php-http/guzzle6-adapter: ^1.1` into require...

**Comment by ashleyhood** [comment]
Guzzle is not a dependency as you can use any php-http client instead or even write your own adaptor.

You will need to add the [php-http client/adaptor](http://docs.php-http.org/en/latest/clients.html) to your composer.json
 ```
composer require php-http/guzzle6-adapter
```
