### ISSUE TITLE
php-http/guzzle7-adapter

### ISSUE THREAD

**Issue by renky** [ashleyhood/php-lxd#26]
Guzzle 7 is there and the first frameworks are already using it (e.g. Laravel 8)
unfortunatelly php-http/guzzle6-adapter doesn't work with Guzzle 7 and the solution of php-http was to create a complete new package php-http/guzzle7-adapter. 
php-http/guzzle7-adapter on the other side needs php-http/httplug 2 and php-lxd requires httplug 1

so how to go on? my suggestion is also switching to Guzzle 7 here and raise the version-number to 0.10- if anybody wants to use guzzle6 he has to stick with 0.9...

what do you think?

**Comment by ashleyhood** [comment]
@renky that sounds like a good approach to upgrade php-http/httplug to v2.2.0 and document in the readme that v0.10 has BC break for package requirements.

Thanks @renky 

Feel free to submit a PR :wink:

**Comment by renky** [comment]
PR created, already tested - some minor fixes have been necessary
can you please create a 0.10 Version? thx
