### ISSUE TITLE
PHP 8.0 compatibility

### ISSUE THREAD

**Issue by C0rn3j** [ashleyhood/php-lxd#28]
Based on a very quick test it looks like the project runs fine on PHP 8.0.

Would it be possible to mark it as such in composer?

```
- opensaucesystems/lxd v0.10.0 requires php ~7.2 -> your PHP version (8.0.0) does not satisfy that requirement.
```

**Comment by ashleyhood** [comment]
I have updated to allow use with PHP 8.0.

Thanks for your input :+1:
