### ISSUE TITLE
Undefined Index "empty"

### ISSUE THREAD

**Issue by renky** [ashleyhood/php-lxd#9]
When creating a new container with option 'alias" there is an PHP Notice about undefined index. That's not so good for environments where error-reporting is set to E_ALL.

PHP Notice:  Undefined index: empty in /var/www/clients/client1/web2/subwebs/test.profi-webspace.eu/vendor/opensaucesystems/lxd/src/Endpoint/Containers.php on line 257

should be added an "isset"-check before check for empty-Value...

**Comment by ashleyhood** [comment]
I would be happy to accept a pull-request ;)
